work_dir: ./work_dir/recognition/ht-stgcn-hand-50-350

# feeder
feeder: feeder.feeder.Feeder #custom feeder disini
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 50
  data_path: ./data/Kinetics/ht_hand_50_350/train_data.npy
  label_path: ./data/Kinetics/ht_hand_50_350/train_label.pkl
test_feeder_args:
  data_path: ./data/Kinetics/ht_hand_50_350/val_data.npy
  label_path: ./data/Kinetics/ht_hand_50_350/val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 7
  dropout: 0.05
  edge_importance_weighting: True
  graph_args:
    #layout: 'openpose'
    layout: 'hand_50'
    strategy: 'spatial'

# training
eval_interval: 1
save_interval: 2
device: [0]
batch_size: 32
test_batch_size: 32

#optim
weight_decay: 0.0001
base_lr: 0.01
#base_lr: 0.1
step: [10, 20, 30, 40, 50]
num_epoch: 50



