work_dir: ./work_dir/recognition/ht-hand-50/ST_GCN_TWO_STREAM

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: ./data/Kinetics/ht-hand-50/train_data.npy
  label_path: ./data/Kinetics/ht-hand-50/train_label.pkl
test_feeder_args:
  data_path: ./data/Kinetics/ht-hand-50/val_data.npy
  label_path: ./data/Kinetics/ht-hand-50/val_label.pkl

# model
model: net.st_gcn_twostream.Model
model_args:
  in_channels: 3
  num_class: 7
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'hand_50'
    strategy: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [10, 50]

# training
device: [0]
batch_size: 32
test_batch_size: 32
num_epoch: 50



